// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: maximum/maximumpb/maximum.proto

package maximumpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Maximum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mx int32 `protobuf:"varint,1,opt,name=mx,proto3" json:"mx,omitempty"`
}

func (x *Maximum) Reset() {
	*x = Maximum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maximum_maximumpb_maximum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Maximum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maximum) ProtoMessage() {}

func (x *Maximum) ProtoReflect() protoreflect.Message {
	mi := &file_maximum_maximumpb_maximum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maximum.ProtoReflect.Descriptor instead.
func (*Maximum) Descriptor() ([]byte, []int) {
	return file_maximum_maximumpb_maximum_proto_rawDescGZIP(), []int{0}
}

func (x *Maximum) GetMx() int32 {
	if x != nil {
		return x.Mx
	}
	return 0
}

type MaximumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Maximum *Maximum `protobuf:"bytes,1,opt,name=maximum,proto3" json:"maximum,omitempty"`
}

func (x *MaximumRequest) Reset() {
	*x = MaximumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maximum_maximumpb_maximum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaximumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaximumRequest) ProtoMessage() {}

func (x *MaximumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maximum_maximumpb_maximum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaximumRequest.ProtoReflect.Descriptor instead.
func (*MaximumRequest) Descriptor() ([]byte, []int) {
	return file_maximum_maximumpb_maximum_proto_rawDescGZIP(), []int{1}
}

func (x *MaximumRequest) GetMaximum() *Maximum {
	if x != nil {
		return x.Maximum
	}
	return nil
}

type MaxiumumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MaxiumumResponse) Reset() {
	*x = MaxiumumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maximum_maximumpb_maximum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxiumumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxiumumResponse) ProtoMessage() {}

func (x *MaxiumumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maximum_maximumpb_maximum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxiumumResponse.ProtoReflect.Descriptor instead.
func (*MaxiumumResponse) Descriptor() ([]byte, []int) {
	return file_maximum_maximumpb_maximum_proto_rawDescGZIP(), []int{2}
}

func (x *MaxiumumResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_maximum_maximumpb_maximum_proto protoreflect.FileDescriptor

var file_maximum_maximumpb_maximum_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x2f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75,
	0x6d, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x22, 0x19, 0x0a, 0x07, 0x4d, 0x61,
	0x78, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x6d, 0x78, 0x22, 0x3c, 0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x6d,
	0x75, 0x6d, 0x2e, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x69,
	0x6d, 0x75, 0x6d, 0x22, 0x2a, 0x0a, 0x10, 0x4d, 0x61, 0x78, 0x69, 0x75, 0x6d, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x5b, 0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x49, 0x0a, 0x0d, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x2e, 0x4d, 0x61, 0x78,
	0x69, 0x6d, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x61,
	0x78, 0x69, 0x6d, 0x75, 0x6d, 0x2e, 0x4d, 0x61, 0x78, 0x69, 0x75, 0x6d, 0x75, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11,
	0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x2f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maximum_maximumpb_maximum_proto_rawDescOnce sync.Once
	file_maximum_maximumpb_maximum_proto_rawDescData = file_maximum_maximumpb_maximum_proto_rawDesc
)

func file_maximum_maximumpb_maximum_proto_rawDescGZIP() []byte {
	file_maximum_maximumpb_maximum_proto_rawDescOnce.Do(func() {
		file_maximum_maximumpb_maximum_proto_rawDescData = protoimpl.X.CompressGZIP(file_maximum_maximumpb_maximum_proto_rawDescData)
	})
	return file_maximum_maximumpb_maximum_proto_rawDescData
}

var file_maximum_maximumpb_maximum_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_maximum_maximumpb_maximum_proto_goTypes = []interface{}{
	(*Maximum)(nil),          // 0: maximum.Maximum
	(*MaximumRequest)(nil),   // 1: maximum.MaximumRequest
	(*MaxiumumResponse)(nil), // 2: maximum.MaxiumumResponse
}
var file_maximum_maximumpb_maximum_proto_depIdxs = []int32{
	0, // 0: maximum.MaximumRequest.maximum:type_name -> maximum.Maximum
	1, // 1: maximum.MaximumService.MaximumStream:input_type -> maximum.MaximumRequest
	2, // 2: maximum.MaximumService.MaximumStream:output_type -> maximum.MaxiumumResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_maximum_maximumpb_maximum_proto_init() }
func file_maximum_maximumpb_maximum_proto_init() {
	if File_maximum_maximumpb_maximum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maximum_maximumpb_maximum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Maximum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maximum_maximumpb_maximum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaximumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maximum_maximumpb_maximum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxiumumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maximum_maximumpb_maximum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maximum_maximumpb_maximum_proto_goTypes,
		DependencyIndexes: file_maximum_maximumpb_maximum_proto_depIdxs,
		MessageInfos:      file_maximum_maximumpb_maximum_proto_msgTypes,
	}.Build()
	File_maximum_maximumpb_maximum_proto = out.File
	file_maximum_maximumpb_maximum_proto_rawDesc = nil
	file_maximum_maximumpb_maximum_proto_goTypes = nil
	file_maximum_maximumpb_maximum_proto_depIdxs = nil
}
