// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package maximumpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MaximumServiceClient is the client API for MaximumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MaximumServiceClient interface {
	MaximumStream(ctx context.Context, opts ...grpc.CallOption) (MaximumService_MaximumStreamClient, error)
}

type maximumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMaximumServiceClient(cc grpc.ClientConnInterface) MaximumServiceClient {
	return &maximumServiceClient{cc}
}

func (c *maximumServiceClient) MaximumStream(ctx context.Context, opts ...grpc.CallOption) (MaximumService_MaximumStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MaximumService_ServiceDesc.Streams[0], "/maximum.MaximumService/MaximumStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &maximumServiceMaximumStreamClient{stream}
	return x, nil
}

type MaximumService_MaximumStreamClient interface {
	Send(*MaximumRequest) error
	Recv() (*MaxiumumResponse, error)
	grpc.ClientStream
}

type maximumServiceMaximumStreamClient struct {
	grpc.ClientStream
}

func (x *maximumServiceMaximumStreamClient) Send(m *MaximumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *maximumServiceMaximumStreamClient) Recv() (*MaxiumumResponse, error) {
	m := new(MaxiumumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaximumServiceServer is the server API for MaximumService service.
// All implementations must embed UnimplementedMaximumServiceServer
// for forward compatibility
type MaximumServiceServer interface {
	MaximumStream(MaximumService_MaximumStreamServer) error
	mustEmbedUnimplementedMaximumServiceServer()
}

// UnimplementedMaximumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMaximumServiceServer struct {
}

func (UnimplementedMaximumServiceServer) MaximumStream(MaximumService_MaximumStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method MaximumStream not implemented")
}
func (UnimplementedMaximumServiceServer) mustEmbedUnimplementedMaximumServiceServer() {}

// UnsafeMaximumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MaximumServiceServer will
// result in compilation errors.
type UnsafeMaximumServiceServer interface {
	mustEmbedUnimplementedMaximumServiceServer()
}

func RegisterMaximumServiceServer(s grpc.ServiceRegistrar, srv MaximumServiceServer) {
	s.RegisterService(&MaximumService_ServiceDesc, srv)
}

func _MaximumService_MaximumStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaximumServiceServer).MaximumStream(&maximumServiceMaximumStreamServer{stream})
}

type MaximumService_MaximumStreamServer interface {
	Send(*MaxiumumResponse) error
	Recv() (*MaximumRequest, error)
	grpc.ServerStream
}

type maximumServiceMaximumStreamServer struct {
	grpc.ServerStream
}

func (x *maximumServiceMaximumStreamServer) Send(m *MaxiumumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *maximumServiceMaximumStreamServer) Recv() (*MaximumRequest, error) {
	m := new(MaximumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaximumService_ServiceDesc is the grpc.ServiceDesc for MaximumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MaximumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maximum.MaximumService",
	HandlerType: (*MaximumServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MaximumStream",
			Handler:       _MaximumService_MaximumStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "maximum/maximumpb/maximum.proto",
}
